### ISSUE TITLE
Truncated error

### ISSUE THREAD

**Issue by alexgleason** [punkave/apostrophe-cli#14]
```
alex@RainbowStar:~/Projects/new-project$ apostrophe create-piece

  error: missing required argument `piec'
```

Not sure why it doesn't say `piece`. A quick search through the code shows no results for `piec`. Wondering if this is being truncated, maybe by shelljs.

Very minor issue, but confusing nontheless.

**Comment by boutell** [comment]
It hates spaces between < and > for some reason. I worked around it with hyphens.
